### ISSUE TITLE
modal is blank

### ISSUE THREAD

**Issue by simbapenn** [mt-support/event-tickets-plus-attendee-data-editor#1]
Appreciate your work on this as it's much needed.  Can't get the user side that's supposed built in to work for editing either.  Anyways, this installs fine for me, but when the window pops open to edit the info, it's blank except for the save button in the top left.  

![screencapture-lowerlabpta-org-testing-wp-admin-edit-php-1516760984189](https://user-images.githubusercontent.com/32891057/35311460-9522ffde-0084-11e8-855b-9806e0d00aec.png)

**Comment by barryhughes** [comment]
Thanks for flagging this!

We're aware of the problem, it's actually the result of a bug in Event Tickets Plus itself (our ref: [#95686](https://central.tri.be/issues/95686)). As soon as that is resolved this also ought to come right. In the interim, there is a workaround that might help you out:

> Make a template override of the orders-edit-meta.php template and use this one https://gist.github.com/vicskf/8a6e772c839e3fcdcd8e84faac8589f7

**Comment by simbapenn** [comment]
Wow, thanks for getting back to me!  I was on the free non-profit license
and literally just purchased so I could get support to get this answered.
I had a feeling it was a bug and I'd have paid for nothing.  Oh well.  It's
worth it to support the devs.  Thanks for your help!

**Comment by simbapenn** [comment]
PS:  Totally worked both on the user side, and using your plugin on the
admin side. Thanks! (fist bump)
